[package]
name = "hoodlum"
version = "0.1.0"
authors = ["Tim Ryan <id@timryan.org>"]
build = "build.rs"
description = "HDL generation library for hardware synthesis."
license = "MIT"
repository = "https://github.com/tcr/hoodlum.git"

[build-dependencies]
lalrpop = "0.11.0"

[dependencies]
lalrpop-util = "0.11.0"
