[package]
name = "hoodlum-parser"
version = "0.4.0"
authors = ["Tim Ryan <id@timryan.org>"]
build = "build.rs"
description = "Parser for the hoodlum crate."
license = "MIT"

[build-dependencies]
lalrpop = "0.12"

[dependencies]
lalrpop-util = "0.12"

[profile.dev]
codegen-units = 8
